[package]
name = "near_token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt_buffer =  { version = "0.1.0", path = "../fmt_buffer" }
numtoa = "0.2.4"
